### 服务端口号
server:
  port: 8888
###eureka 基本信息配置 
eureka:
  instance:
###注册到eureka的ip地址
    hostname: localhost
  client:
###因为自己是为注册中心，不需要自己注册自己
    registerWithEureka: false
###因为自己是为注册中心，不需要检索服务
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
